### ISSUE TITLE
Complex connection strings aren't parsed correctly from the command line.

### ISSUE THREAD

**Issue by ianjevans** [cockroachlabs/hello-world-python-psycopg2#3]
If you use a connection string to CockroachCloud free tier clusters, you can't specify e.g. the `sslrootcert` and other parameters within the connection string from the command line.

```
python3 example.py postgres://<password>@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/bank?sslmode=verify-full&sslrootcert=<path>/cc-ca.crt&options=--cluster=<cluster_name>
```

Everything after `sslmode=verify-full` is ignored, so psycopg2 uses the default path to the root cert (`~/.postgresql/root.crt`).

The workaround is to surround the connection string with single quotes.

```
python3 example.py 'postgres://<password>@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/bank?sslmode=verify-full&sslrootcert=<path>/cc-ca.crt&options=--cluster=<cluster_name>'
```

**Comment by ianjevans** [comment]
I suspect there's something weird going on with `psycopg2.extensions.parse_dsn()`, or the ampersand is not being handled by `argparse.ArgumentParser.parse_args()` or both.

**Comment by ianjevans** [comment]
Looking most likely that it's due to the cluster name not being parsed by `parse_dsn`.
```
ProgrammingError                          Traceback (most recent call last)
<ipython-input-9-ca769c3be6ea> in <module>
----> 1 parse_dsn('postgres://user:password@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/bank?sslmode=verify-full&sslrootcert=/Users/laurenhirata/cc/certs/cc-ca.crt&options=--cluster=gummy-fox-126')

ProgrammingError: invalid dsn: extra key/value separator "=" in URI query parameter: "options"
```

So we can set the cluster-name as a prefix to the database name, or maybe URL encode the equals character in `cluster=whatever`.

**Comment by dvarrazzo** [comment]
The original problem is most likely due to bash interpreting the `&` as an operator to put the process in background and the right solution is to quote the argument.

The canonical way is to use double quotes on the command line, so that eventual environment variables can be expanded.

The `=` in the value should be percent-escaped as `%3d`:
```
In [11]: psycopg2.extensions.parse_dsn("postgres://<password>@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/ban
    ...: k?sslmode=verify-full&sslrootcert=<path>/cc-ca.crt&options=--cluster%3d<cluster_name>")
Out[11]: 
{'user': '<password>',
 'dbname': 'bank',
 'host': 'free-tier.gcp-us-central1.cockroachlabs.cloud',
 'port': '26257',
 'options': '--cluster=<cluster_name>',
 'sslmode': 'verify-full',
 'sslrootcert': '<path>/cc-ca.crt'}
```

**Comment by dvarrazzo** [comment]
IMO, on the command line, using the conninfo syntax is more readable and, because you need to use quotes as soon as you have more than one argument, there are less problems with special characters. Also the problem of having an = in a value is not a problem: the conninfo parser treats following = as part of the value. 

```
python3 example.py "user=<password> dbname=bank host=free-tier.gcp-us-central1.cockroachlabs.cloud port=26257 options=--cluster=<cluster_name> sslmode=verify-full sslrootcert=<path>/cc-ca.crt"
```

In case the value has other funny characters they can be represented in single quotes.

```
print(psycopg2.extensions.make_dsn(host="foo=bar", user="take that!"))
host=foo=bar user='take that!'
```

**Comment by ianjevans** [comment]
Closing as we now pick up the connection string in an environment variable.
